[project]
name = "leandro-berti-entrega-final-60095"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
]

[dependency-groups]
dev = [
    "ipython>=8.30.0",
]
